version: "3.7"

networks:
  apps:
    external: true
  nextcloud:

volumes:
  nextcloud-apps:
  nextcloud-config:
  nextcloud-data:
  nextcloud-postgres:
  nextcloud-elasticsearch:
  nextcloud-redis:

services:
  nextcloud:
    build: ./nextcloud
    image: local/nextcloud
    networks:
      - apps
      - nextcloud
    env_file: .env
    volumes:
      - nextcloud-apps:/var/www/html/custom_apps
      - nextcloud-config:/var/www/html/config
      - nextcloud-data:/var/www/html/data"
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "true"
        traefik.backend: nextcloud
        traefik.port: 80
        traefik.frontend.rule: Host:cloud.${DOMAIN}
        traefik.frontend.headers.customFrameOptionsValue: "DENY"
        traefik.frontend.headers.contentTypeNosniff: "true"
        traefik.frontend.headers.browserXSSFilter: "true"

  postgres:
    build: ./postgres
    image: local/postgres
    networks:
      - nextcloud
    env_file: .env
    volumes:
      - nextcloud-postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    networks:
      - nextcloud
    sysctls:
      - net.core.somaxconn=4096
      # - vm.overcommit_memory=1
    volumes:
      - nextcloud-redis:/data

  elasticsearch:
    build: ./elasticsearch
    image: local/elasticsearch-oss
    networks:
      - nextcloud
    env_file: .env
    # sysctls:
    #   - vm.max_map_count=262144 # bug OCI runtime create failed: sysctl "vm.max_map_count" is not in a separate kernel namespace: unknown https://github.com/moby/moby/issues/30778
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - nextcloud-elasticsearch:/usr/share/elasticsearch/data
